# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4597683f9e8b23593edb9b9ab1caccff1b839a34ccd05d1b1e0beb5b9615dadd72d2c0b5256b8e146c62bb0e096c761355ad244726cc86eb1bf59634c92c8947

test:
  secret_key_base: fa090995381d8d539a5d5580161bea88bb413ff86372885c2260c7804c0aa184d31dac6eb4ed6714f536d78e0725fd80bf9f34d92d79ad6b30ddad7758d53328

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
